# Generated by Django 2.0.2 on 2018-03-09 07:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=False, max_length=20)),
                ('desc', models.CharField(default=False, max_length=140)),
                ('tags', models.CharField(default=False, max_length=140)),
                ('location', models.CharField(default=False, max_length=140)),
                ('rsvp_date', models.DateField(blank=True, default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
