# Generated by Django 2.0.2 on 2018-02-20 06:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='question',
        ),
        migrations.AddField(
            model_name='organization',
            name='users',
            field=models.ManyToManyField(related_name='organizations', to='main.User'),
        ),
        migrations.AddField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.CharField(default=False, max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='pword',
            field=models.CharField(default=False, max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default=False, max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='zipcode',
            field=models.CharField(default=False, max_length=5),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(default=False, max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(default=False, max_length=20),
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
